### ISSUE TITLE
install failing at COGtriangles step 

### ISSUE THREAD

**Issue by korinalb** [eead-csic-compbio/get_homologues#30] opened 2018-06-21 13:17 UTC
I'm trying to install get_homologues on a computing cluster. The cluster does not have a COGtriangles module pre-loaded.

I followed the steps in the manual to compile COGtriangles with g++/8.1.0.

It seems like COGtriangles, COGmakeblast, COGcognitor, and COGmakehash were all made properly once I added

`#include <unistd.h>`

to the top of the os.h files in COGcoginitor and COGtriangles, and the bc.h file in COGreadblast as per this site: [http://seqanswers.com/forums/archive/index.php/t-51326.html]

However, I'm still getting this error when I try to install get_homologues:

```
[ka41a@ghpcc06 homo]$ perl install.pl

### 1) checking required parts: 

## checking whether source and binaries of dependencies are in place
>> OK

## checking mcl-14-137 (lib/phyTools: $ENV{'EXE_MCL'})
>> OK
## checking COGsoft/COGtriangles (lib/phyTools: $ENV{'EXE_COGTRI'})

# compiling COGsoft/COGtriangles ...
g++ -O3 -g -Wall  -c cogtriangles.cpp
In file included from cogtriangles.cpp:5:
os.h: In function ‘void myOpenDir(const char*)’:
os.h:13:7: error: ‘chdir’ was not declared in this scope
   if (chdir(dirpath))
       ^~~~~
os.h:13:7: note: suggested alternative: ‘char’
   if (chdir(dirpath))
       ^~~~~
       char
make: *** [cogtriangles.o] Error 1
<< Cannot run COGtriangles, please check the manual for compilation instructions and re-run.
```
So even though I get the message below when I make COGtriangles, get_homologues doesn't recognize it and keeps failing during the install.
```
[ka41a@ghpcc06 COGtriangles]$ cd ../COGtriangles;make
make: `COGtriangles' is up to date.
```
Could someone give me any help with this? I can install and run get_homologues on my personal computer just fine, but I just can't get it installed on a computing cluster.
Thank you!!
-Korin

**Comment by eead-csic-compbio** [comment] 2018-06-21 18:38
Hi Korin,
I just installed g++-8 in my ubuntu 18.04 and compiled all four COG binaries manually with:
$ make clean; make
All of them compiled successfully with no need to change os.h. In fact, if you check os.h in COGtriangles folder, you'll see it does #include <unistd.h> when _GNUG_ is defined, which is set by g++ compilers. So, I cannot reproduce your error right now. Please make sure you are  using g++ for compilation, Bruno

**Comment by eead-csic-compbio** [comment] 2018-06-21 18:40
In addition, if you managed to compile them manually, install.pl will not compile them again, so please make sure that you compile the sources in the bin/COGsoft folder, Bruno

**Comment by eead-csic-compbio** [comment] 2018-09-30 00:00
See commit https://github.com/eead-csic-compbio/get_homologues/commit/bad746c8b74a16d4deb576955e3825191eb08324, this should be fixed now, thanks

**Closed by eead-csic-compbio** 2018-09-30 00:00 UTC
