### ISSUE TITLE
pangenome_matrix_t0.tab display hash reference instead of 1s

### ISSUE THREAD

**Issue by ABTsutenkyo** [eead-csic-compbio/get_homologues#16] opened 2017-08-25 14:16 UTC
Hello! 

First of all, thank you for your amazing program (using the latest release, 20170807). 
I have an issue though, with the pangenome_matrix_t0.tab file generated by compare_clusters.pl . 
Instead of 1s, it displays hash references (eg : HASH(0x338d6b8)). I've been trying to debug it for a while, even using your commented line in compare_clusters.pl to "artificially" print 1s instead (to later use that matrix with the plot_matrix_heatmap.sh, which returns me "Error in read.table(file = "0824_intersect_pangenome/pangenome_matrix_t0.tab",  : more columns than columns names"). 
I'm out of ideas for now, could you help me resolve the issue? Idk if the bug lies in my data, in my R dependencies, or else... 

Thanks a lot,
Cheers,

Audrey

**Comment by ABTsutenkyo** [comment] 2017-08-25 20:33
Actually I think I got a partial answer. 
When I look at a conserved_gene.faa file generated with the get_homologues COG algorithm, I realise I can have n-times the exact same taxon (let's say "[Proteus mirabilis]") for different genbank input files. I believe the taxon has been merged while generating the pangenome_matrix, thus the hash and columns mix up. 
I thought the compare_clusters.pl used genbank filenames to generate the matrix' rows, not the taxon?... 
Investigation in progress.

Thanks in advance for your help,
Cheers,

Audrey

**Comment by eead-csic-compbio** [comment] 2017-08-27 09:53
Thanks for your message Audrey, we had a similar issue solved some releases ago. I just produced a pangenome_matrix.tab with the sample_buch_fasta dataset and it looks all correct. If you would send me a link to a compressed folder with your COG clusters and the .cluster.list file I can try to reproduce your problem. Perhaps you prefer to send it to my email at bcontreras@eead.csic.es, cheers

**Comment by eead-csic-compbio** [comment] 2017-08-28 15:00
Hi Audrey, I was able to reproduce your reported issue and can confirm it was a bug in _compare_clusters.pl_ due to previous changes in find_taxa_FASTA_array_headers. This was not spotted earlier as was only affecting jobs where *.cluster_list files (one per input folder) were not parsed. Although the code is fixed in release v3.0.7, we recommend you do your analyses with the attached .cluster_list files produced by _get_homologues.pl_. If you call _compare_clusters.pl_ passing the original cluster folders, for instance produced by OMCL and COG, the script will find those .cluster_list files for you. If it fails to do so, it will print the following warning:

 # no cluster list in place, checking directory content ...
# WARNING: [taxon names] will be automatically extracted from FASTA headers,
# please watch out for errors

This is error-prone as strains of the same species often have the same [taxon name] in their FASTA headers. When cluster_list are in place, sequences are correctly assigned to taxa, which is probably what you expect, right?
Thanks for reporting it, Bruno

**Closed by eead-csic-compbio** 2017-08-28 15:00 UTC
