### ISSUE TITLE
Having installation problem

### ISSUE THREAD

**Issue by ntam97** [eead-csic-compbio/get_homologues#61] opened 2020-07-08 16:51 UTC
Hello,

I am hoping to utilize this program for my personal research. I am relatively new to coding and bioinformatics overall. I have the software installed along with the required dependencies. However, I keep getting message that some of the dependencies are not in the right place.  

"EXE_BLASTP :  needs to be installed (wrong path:/Users/Tam/get_homologues/bin/ncbi-blast-2.8.1+/bin/blastp)
 EXE_BLASTN :  needs to be installed (wrong path:/Users/Tam/get_homologues/bin/ncbi-blast-2.8.1+/bin/blastn)
      EXE_FORMATDB :  needs to be installed (wrong path:/Users/Tam/get_homologues/bin/ncbi-blast-2.8.1+/bin/makeblastdb)
           EXE_MCL : OK (path:/Users/Tam/get_homologues//bin/mcl-14-137/src/shmcl/mcl)
      EXE_MAKEHASH :  needs to be installed (wrong path:/Users/Tam/get_homologues//bin/COGsoft/COGmakehash/COGmakehash )
     EXE_READBLAST :  needs to be installed (wrong path:/Users/Tam/get_homologues//bin/COGsoft/COGreadblast/COGreadblast )
        EXE_COGLSE :  needs to be installed (wrong path:/Users/Tam/get_homologues//bin/COGsoft/COGlse/COGlse )
        EXE_COGTRI :  needs to be installed (wrong path:/Users/Tam/get_homologues//bin/COGsoft/COGtriangles/COGtriangles )
       EXE_HMMPFAM :  needs to be installed (wrong path:/Users/Tam/get_homologues//bin/hmmer-3.1b2/binaries/hmmscan --noali --acc --cut_ga )
         EXE_DMNDP : OK (path:/Users/Tam/get_homologues/bin/diamond-0.8.25/diamond blastp)
         EXE_DMNFT : OK (path:/Users/Tam/get_homologues/bin/diamond-0.8.25/diamond makedb)
        EXE_INPARA : OK (path:/Users/Tam/get_homologues/_cluster_makeInparalog.pl)
         EXE_ORTHO : OK (path:/Users/Tam/get_homologues/_cluster_makeOrtholog.pl)
         EXE_HOMOL : OK (path:/Users/Tam/get_homologues/_cluster_makeHomolog.pl)
    EXE_SPLITBLAST : OK (path:/Users/Tam/get_homologues/_split_blast.pl)
  EXE_SPLITHMMPFAM : OK (path:/Users/Tam/get_homologues/_split_hmmscan.pl)"

I am not sure what I can do so I can have all the required dependencies in the right place to run program. I would really appreciate it if you could give me some insights. Thank you!

Best,
Tam

**Comment by brunocontrerasmoreira** [comment] 2020-07-08 18:25
Hi Tam,
I assume you are using a cloned GitHub repository?
In that case after cloning you should do:
cd get_homologues
perl install.pl

After that's done you should be able to run the software from anywhere in your machine provided that you use the right path. I mean something like this: 
perl ~/soft/get_homologues/get_homologues.pl -d ...

Let me know if this helps,
Bruno

**Comment by ntam97** [comment] 2020-07-08 18:50
Hi,

Thank you for your help! I think I am close to getting it installed. I am still getting blastp, blastn, formatdb and hmmpfam need to be installed though they are already in the bin in the right path. I think I am still missing a step... 

Best,
Tam

**Comment by brunocontrerasmoreira** [comment] 2020-07-09 07:49
Hi Tam,
there are several ways of installing and running GET_HOMOLOGUES (tar file, github, docker).
Can you please confirm which way you chose and what operating system you have?

1) What happens if you run ```/Users/Tam/get_homologues/bin/ncbi-blast-2.8.1+/bin/blastp``` on the command line? Can you paste here the output?

2) Same with ```/Users/Tam/get_homologues//bin/COGsoft/COGmakehash/COGmakehash```

Thanks,
Bruno

**Comment by ntam97** [comment] 2020-07-09 12:21
Hello,

I git cloned the program. I am using Mac OS X El Capitan version 10.11.6. 

When I run the command line the blast, this is what I get: -bash: /Users/Tam/get_homologues/bin/ncbi-blast-2.8.1+/bin/blastp: cannot execute binary file

When I run the command for COGsoft: Can't open output file ./conv/hash.csv

Sorry for the inconvenience! I am trying to figure it out by myself but I am still so new to all of this. Thanks again! 

Tam

**Comment by brunocontrerasmoreira** [comment] 2020-07-09 12:23
Hi, did you get the binaries by running $ perl install.pl?
Can you do $ file /Users/Tam/get_homologues/bin/ncbi-blast-2.8.1+/bin/blastp ?

**Comment by ntam97** [comment] 2020-07-09 12:30
I did run the $ perl install. pl and I got a message saying
## Checking blast (lib/phyTools: $ENV{'EXE_BLASTP'})
<< Cannot run shipped blastp, please download it from ftp.ncbi.nih.gov/blast/executables/blast+/LATEST/ ,
<< install it and edit variable BLAST_PATH as explained in the manual
<< (inside set_phyTools_env in file lib/phyTools.pm) .
<< Then re-run

I ran the $ file /Users/Tam/get_homologues/bin/ncbi-blast-2.8.1+/bin/blastp and got the following: /Users/Tam/get_homologues/bin/ncbi-blast-2.8.1+/bin/blastp: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, stripped

**Comment by brunocontrerasmoreira** [comment] 2020-07-09 12:33
Ok it seems you got the wrong binaries for some reason. I will try to make a fresh install on a Mac I have next to me to double-check this is not a bug in install.pl

**Comment by ntam97** [comment] 2020-07-09 12:38
Thank you so much!

**Comment by brunocontrerasmoreira** [comment] 2020-07-09 12:43
I tried the following on a macOS Catalina:

git clone https://github.com/eead-csic-compbio/get_homologues.git

perl install.pl

The key piece of output during installation is: "# operating system guess: macOSX"

It all went ok and the code works. When I do:

file ncbi-blast-2.8.1+/bin/blastp

I get 

ncbi-blast-2.8.1+/bin/blastp: Mach-O 64-bit executable x86_64

**Comment by ntam97** [comment] 2020-07-09 12:51
So I started fresh and I think I have to download your latest bin folder since I git cloned the link. None of the required dependencies are in the bin file.

**Comment by brunocontrerasmoreira** [comment] 2020-07-09 12:56
The install.pl script should download the right binaries for you

**Comment by ntam97** [comment] 2020-07-09 13:17
It appears I don't have wget installed and I think that is giving me problem. I will keep trying. 

Best,
Tam

**Comment by brunocontrerasmoreira** [comment] 2020-07-09 13:26
Thanks for spotting that,
you can install it as explained in 

https://www.fossmint.com/install-and-use-wget-on-mac/

Or alternatively download https://github.com/eead-csic-compbio/get_homologues/releases/download/v3.3.3/binosx.tgz and upack it in the bin folder

Can you confirm you have curl? I will see to use that under macOS, 
Bruno

**Comment by ntam97** [comment] 2020-07-09 13:45
I will for sure install wget. I do have curl.

**Comment by ntam97** [comment] 2020-07-09 14:11
I realized my desktop is an older mac version (10.11.6) and it seems like neither brew nor xcode is supported by this version which eventually prevents me from installing any required compilers to use your program. I am sure your program is perfectly fine. I just need to figure out how to upgrade my desktop. 

Best,
Tam

**Comment by brunocontrerasmoreira** [comment] 2020-07-09 14:17
I have updated install.pl so that it will try curl before wget in macOS. If you do git pull you'll get it and you can try it out. Your feedback is appreciated,
Bruno

**Comment by ntam97** [comment] 2020-07-09 14:25
I was able to install. Thank you so so much for your help! I truly appreciate it. 

Best,
Tam

**Comment by brunocontrerasmoreira** [comment] 2020-07-09 14:26
Cool, I close this now then.

**Comment by ntam97** [comment] 2020-07-09 14:27
Yes. Thank you so much! Have a nice week!

Tam

**Closed** 2020-07-09 14:28 UTC
